### PR TITLE
Add tailwind and prteeier

### PR DESCRIPTION
**Pull request by Aaqu**
Sorry for mess, I've added protection on main. Will there be any of this?

### CODE REVIEW

**Comment by MJanowskiDev** [comment]
Thanks @Aaqu for first PR!
I accept PR to be merged into main. 
.eslintrc.json - OK
.prettierignore - Prettier's CLI ignores node_modules by default - OK
.vscode/settings.json - OK
postcss.config.js - OK 
prettier.config.js - OK
tailwind.config.js - OK

**Review by MJanowskiDev — DISMISSED** [review]
Thanks @Aaqu for first PR!
I accept PR to be merged into main. 
.eslintrc.json - OK
.prettierignore - Prettier's CLI ignores node_modules by default - OK
.vscode/settings.json - OK
postcss.config.js - OK 
prettier.config.js - OK
tailwind.config.js - OK

**Review by gosiajaninska — APPROVED** [review]

**Review by gosiajaninska — APPROVED** [review]

**Review by gosiajaninska — APPROVED** [review]

**Review by gosiajaninska — APPROVED** [review]

**Review by MJanowskiDev — APPROVED** [review]
Thanks @Aaqu for first PR!
I accept PR to be merged into main.
.eslintrc.json - OK
.prettierignore - Prettier's CLI ignores node_modules by default - OK
.vscode/settings.json - OK
postcss.config.js - OK 
prettier.config.js - OK
tailwind.config.js - OK

**Review by gosiajaninska — APPROVED** [review]
approve

**Review by gosiajaninska — APPROVED** [review]

**Review by gosiajaninska — APPROVED** [review]
ok

**Pull request merged**
